version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: sazman_backend
    restart: on-failure
    command:
      [
        "uvicorn",
        "main:app_socket",
        "--host",
        "0.0.0.0",
        "--workers",
        "1",
        "--log-level",
        "debug",
      ]
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./backend/certs:/app/certs
    environment:
      PYTHONUNBUFFERED: 1 # Ensure logs are flushed immediately
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.4
    container_name: sazman_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:6.2.13
    container_name: sazman_redis
    restart: on-failure
    ports:
      - "6379:6379"

  frontend:
    image: nginx:1.22
    container_name: sazman_frontend
    restart: on-failure
    volumes:
      - ./frontend/build/web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - backend

  celery_worker:
    build:
      context: ./backend
    container_name: sazman_celery_worker
    command: celery -A task_manager.celery_app worker --loglevel=info
    depends_on:
      - redis
      - backend

# networks:
#   custom_network: # Define a custom bridge network
#     driver: bridge

volumes:
  postgres_data:
    driver: local
