"""Initial tables

Revision ID: 47d8cd835256
Revises:
Create Date: 2024-12-24 21:12:39.113947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d8cd835256'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=True)
    op.create_table('camera_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('setting_type', sa.Enum('INT', 'FLOAT', 'STRING', name='settingtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_settings_id'), 'camera_settings', ['id'], unique=False)
    op.create_index(op.f('ix_camera_settings_name'), 'camera_settings', ['name'], unique=True)
    op.create_table('lpr_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('setting_type', sa.Enum('INT', 'FLOAT', 'STRING', name='lprsettingtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lpr_settings_id'), 'lpr_settings', ['id'], unique=False)
    op.create_index(op.f('ix_lpr_settings_name'), 'lpr_settings', ['name'], unique=True)
    op.create_table('lprs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lprs_id'), 'lprs', ['id'], unique=False)
    op.create_index(op.f('ix_lprs_ip'), 'lprs', ['ip'], unique=False)
    op.create_index(op.f('ix_lprs_name'), 'lprs', ['name'], unique=True)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    op.create_table('traffic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix_2', sa.String(), nullable=False),
    sa.Column('alpha', sa.String(), nullable=False),
    sa.Column('mid_3', sa.String(), nullable=False),
    sa.Column('suffix_2', sa.String(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ocr_accuracy', sa.Float(), nullable=True),
    sa.Column('vision_speed', sa.Float(), nullable=True),
    sa.Column('camera_name', sa.String(), nullable=True),
    sa.Column('gate_name', sa.String(), nullable=True),
    sa.Column('plate_image_path', sa.String(), nullable=True),
    sa.Column('full_image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_camera_name'), 'traffic', ['camera_name'], unique=False)
    op.create_index(op.f('ix_traffic_gate_name'), 'traffic', ['gate_name'], unique=False)
    op.create_index(op.f('ix_traffic_id'), 'traffic', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_plate_number'), 'traffic', ['plate_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('national_id', sa.String(length=10), nullable=False),
    sa.Column('personal_number', sa.String(length=10), nullable=False),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('ADMIN', 'STAFF', 'USER', 'VIEWER', name='usertype'), nullable=False),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('password_changed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id'),
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_personal_number'), 'users', ['personal_number'], unique=True)
    op.create_table('gates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gate_type', sa.Enum('ENTRANCE', 'EXIT', 'BOTH', name='gatetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gates_id'), 'gates', ['id'], unique=False)
    op.create_index(op.f('ix_gates_name'), 'gates', ['name'], unique=True)
    op.create_table('lpr_setting_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('setting_type', sa.Enum('INT', 'FLOAT', 'STRING', name='lprsettingtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('lpr_id', sa.Integer(), nullable=False),
    sa.Column('default_setting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_setting_id'], ['lpr_settings.id'], ),
    sa.ForeignKeyConstraint(['lpr_id'], ['lprs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lpr_setting_instances_id'), 'lpr_setting_instances', ['id'], unique=False)
    op.create_index(op.f('ix_lpr_setting_instances_name'), 'lpr_setting_instances', ['name'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('vehicle_class', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('vehicle_color', sa.String(), nullable=True),
    sa.Column('car_image', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('gate_id', sa.Integer(), nullable=False),
    sa.Column('lpr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['lpr_id'], ['lprs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_index(op.f('ix_cameras_name'), 'cameras', ['name'], unique=True)
    op.create_table('traffic_vehicle_association',
    sa.Column('traffic_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['traffic_id'], ['traffic.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('traffic_id', 'vehicle_id')
    )
    op.create_table('camera_lpr_association',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('lpr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lpr_id'], ['lprs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('camera_id', 'lpr_id')
    )
    op.create_table('camera_setting_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('setting_type', sa.Enum('INT', 'FLOAT', 'STRING', name='settingtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('default_setting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['default_setting_id'], ['camera_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_setting_instances_id'), 'camera_setting_instances', ['id'], unique=False)
    op.create_index(op.f('ix_camera_setting_instances_name'), 'camera_setting_instances', ['name'], unique=False)

    op.create_table('viewer_gate_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'gate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewer_gate_access')
    op.drop_index(op.f('ix_camera_setting_instances_name'), table_name='camera_setting_instances')
    op.drop_index(op.f('ix_camera_setting_instances_id'), table_name='camera_setting_instances')
    op.drop_table('camera_setting_instances')
    op.drop_table('camera_lpr_association')
    op.drop_table('traffic_vehicle_association')
    op.drop_index(op.f('ix_cameras_name'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_lpr_setting_instances_name'), table_name='lpr_setting_instances')
    op.drop_index(op.f('ix_lpr_setting_instances_id'), table_name='lpr_setting_instances')
    op.drop_table('lpr_setting_instances')
    op.drop_index(op.f('ix_gates_name'), table_name='gates')
    op.drop_index(op.f('ix_gates_id'), table_name='gates')
    op.drop_table('gates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_traffic_plate_number'), table_name='traffic')
    op.drop_index(op.f('ix_traffic_id'), table_name='traffic')
    op.drop_index(op.f('ix_traffic_gate_id'), table_name='traffic')
    op.drop_index(op.f('ix_traffic_camera_id'), table_name='traffic')
    op.drop_table('traffic')
    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_lprs_name'), table_name='lprs')
    op.drop_index(op.f('ix_lprs_ip'), table_name='lprs')
    op.drop_index(op.f('ix_lprs_id'), table_name='lprs')
    op.drop_table('lprs')
    op.drop_index(op.f('ix_lpr_settings_name'), table_name='lpr_settings')
    op.drop_index(op.f('ix_lpr_settings_id'), table_name='lpr_settings')
    op.drop_table('lpr_settings')
    op.drop_index(op.f('ix_camera_settings_name'), table_name='camera_settings')
    op.drop_index(op.f('ix_camera_settings_id'), table_name='camera_settings')
    op.drop_table('camera_settings')
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
