"""Fixed user-vehicle relation

Revision ID: 55bf67eab1ad
Revises: 68273d3b535e
Create Date: 2025-01-22 20:20:57.645229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bf67eab1ad'
down_revision: Union[str, None] = '68273d3b535e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gates_building_id_fkey', 'gates', type_='foreignkey')
    op.create_foreign_key(None, 'gates', 'buildings', ['building_id'], ['id'])
    op.drop_constraint('lpr_setting_instances_lpr_id_fkey1', 'lpr_setting_instances', type_='foreignkey')
    op.alter_column('users', 'personal_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'national_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint('vehicles_owner_id_fkey', 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key('vehicles_owner_id_fkey', 'vehicles', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'national_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('users', 'personal_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_foreign_key('lpr_setting_instances_lpr_id_fkey1', 'lpr_setting_instances', 'lprs', ['lpr_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'gates', type_='foreignkey')
    op.create_foreign_key('gates_building_id_fkey', 'gates', 'buildings', ['building_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
